float:
  any:
  # 1-bit quantization
  - base_args: ['@metric', 1]
    constructor: PGDiskANN
    disabled: false
    docker_tag: ann-benchmarks-pgvectorscale
    module: ann_benchmarks.algorithms.pgvectorscale
    name: pgvectorscale1
    run_groups:
      N-16-64-ALPHA-1.2:
        arg_groups: [{num_neighbors: 16, search_list_size: 64, max_alpha: 1.2}]
        query_args: [[20, 40, 60]]
      N-24-64-ALPHA-1.2:
        arg_groups: [{num_neighbors: 24, search_list_size: 64, max_alpha: 1.2}]
        query_args: [[20, 40, 60]]
      N-16-128-ALPHA-1.2:
        arg_groups: [{num_neighbors: 16, search_list_size: 128, max_alpha: 1.2}]
        query_args: [[20, 40, 60]]
      N-24-128-ALPHA-1.2:
        arg_groups: [{num_neighbors: 24, search_list_size: 128, max_alpha: 1.2}]
        query_args: [[20, 40, 60]]
      N-16-64-ALPHA-1.5:
        arg_groups: [{num_neighbors: 16, search_list_size: 64, max_alpha: 1.5}]
        query_args: [[20, 40, 60]]
      N-24-64-ALPHA-1.5:
        arg_groups: [{num_neighbors: 24, search_list_size: 64, max_alpha: 1.5}]
        query_args: [[20, 40, 60]]
      N-16-128-ALPHA-1.5:
        arg_groups: [{num_neighbors: 16, search_list_size: 128, max_alpha: 1.5}]
        query_args: [[20, 40, 60]]
      N-24-128-ALPHA-1.5:
        arg_groups: [{num_neighbors: 24, search_list_size: 128, max_alpha: 1.5}]
        query_args: [[20, 40, 60]]
  
  # 8-bit quantization  
  - base_args: ['@metric', 8]
    constructor: PGDiskANN
    disabled: false
    docker_tag: ann-benchmarks-pgvectorscale
    module: ann_benchmarks.algorithms.pgvectorscale
    name: pgvectorscale8
    run_groups:
      N-16-64-ALPHA-1.2:
        arg_groups: [{num_neighbors: 16, search_list_size: 64, max_alpha: 1.2}]
        query_args: [[20, 40, 60]]
      N-24-64-ALPHA-1.2:
        arg_groups: [{num_neighbors: 24, search_list_size: 64, max_alpha: 1.2}]
        query_args: [[20, 40, 60]]
      N-16-128-ALPHA-1.2:
        arg_groups: [{num_neighbors: 16, search_list_size: 128, max_alpha: 1.2}]
        query_args: [[20, 40, 60]]
      N-24-128-ALPHA-1.2:
        arg_groups: [{num_neighbors: 24, search_list_size: 128, max_alpha: 1.2}]
        query_args: [[20, 40, 60]]
      N-16-64-ALPHA-1.5:
        arg_groups: [{num_neighbors: 16, search_list_size: 64, max_alpha: 1.5}]
        query_args: [[20, 40, 60]]
      N-24-64-ALPHA-1.5:
        arg_groups: [{num_neighbors: 24, search_list_size: 64, max_alpha: 1.5}]
        query_args: [[20, 40, 60]]
      N-16-128-ALPHA-1.5:
        arg_groups: [{num_neighbors: 16, search_list_size: 128, max_alpha: 1.5}]
        query_args: [[20, 40, 60]]
      N-24-128-ALPHA-1.5:
        arg_groups: [{num_neighbors: 24, search_list_size: 128, max_alpha: 1.5}]
        query_args: [[20, 40, 60]]

  # 4-bit quantization  
  - base_args: ['@metric', 4]
    constructor: PGDiskANN
    disabled: false
    docker_tag: ann-benchmarks-pgvectorscale
    module: ann_benchmarks.algorithms.pgvectorscale
    name: pgvectorscale4
    run_groups:
      N-16-64-ALPHA-1.2:
        arg_groups: [{num_neighbors: 16, search_list_size: 64, max_alpha: 1.2}]
        query_args: [[20, 40, 60]]
      N-24-64-ALPHA-1.2:
        arg_groups: [{num_neighbors: 24, search_list_size: 64, max_alpha: 1.2}]
        query_args: [[20, 40, 60]]
      N-16-128-ALPHA-1.2:
        arg_groups: [{num_neighbors: 16, search_list_size: 128, max_alpha: 1.2}]
        query_args: [[20, 40, 60]]
      N-24-128-ALPHA-1.2:
        arg_groups: [{num_neighbors: 24, search_list_size: 128, max_alpha: 1.2}]
        query_args: [[20, 40, 60]]
      N-16-64-ALPHA-1.5:
        arg_groups: [{num_neighbors: 16, search_list_size: 64, max_alpha: 1.5}]
        query_args: [[20, 40, 60]]
      N-24-64-ALPHA-1.5:
        arg_groups: [{num_neighbors: 24, search_list_size: 64, max_alpha: 1.5}]
        query_args: [[20, 40, 60]]
      N-16-128-ALPHA-1.5:
        arg_groups: [{num_neighbors: 16, search_list_size: 128, max_alpha: 1.5}]
        query_args: [[20, 40, 60]]
      N-24-128-ALPHA-1.5:
        arg_groups: [{num_neighbors: 24, search_list_size: 128, max_alpha: 1.5}]
        query_args: [[20, 40, 60]]