float:
  any:
  - base_args: ['@metric']
    constructor: PGVector
    disabled: false
    docker_tag: ann-benchmarks-pgvector
    module: ann_benchmarks.algorithms.pgvector
    name: pgvector
    run_groups:
      M-16-64:
        arg_groups: [{M: 16, efConstruction: 64}]
        args: {}
        query_args: [[20,40,60]]
      M-24-64:
        arg_groups: [{M: 24, efConstruction: 64}]
        args: {}
        query_args: [[20,40,60]]
      M-16-128:
        arg_groups: [{M: 16, efConstruction: 128}]
        args: {}
        query_args: [[20,40,60]]
      M-24-128:
        arg_groups: [{M: 24, efConstruction: 128}]
        args: {}
        query_args: [[20,40,60]]
