float:
  any:
    - base_args: ["@metric", "@dimension"]
      constructor: MilvusHNSW
      disabled: false
      docker_tag: ann-benchmarks-milvus
      module: ann_benchmarks.algorithms.milvus
      name: milvus-hnsw
      run_groups:
        HNSW:
          args:
            M: [16,24]
            efConstruction: [64,128]
          query_args: [[20,40,60]]
    - base_args: ["@metric", "@dimension"]
      constructor: MilvusHNSW_SQ
      disabled: false
      docker_tag: ann-benchmarks-milvus
      module: ann_benchmarks.algorithms.milvus
      name: milvus-hnsw-sq
      run_groups:
        HNSW:
          args:
            M: [16,24]
            sqType: ["SQ6", "SQ8","BF16"]
            efConstruction: [64,128]
          query_args: [[20,40,60]]
